# Use postgres/example user/password credentials
version: '3.9'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '${PORT}:3000'
    depends_on:
      - db
      - adminer
    volumes:
      - .:/src
    networks:
      - node-network
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    networks:
      - node-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
